name: netflix_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  bordered_text: ^2.0.0
  dartz: ^0.10.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  injectable: ^1.5.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  share_plus: 4.0.3
  video_player: 2.3.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
